### ISSUE TITLE
NameError: name 'PencilDrawing' is not defined

### ISSUE THREAD

**Issue by iairose** [candycat1992/PencilDrawing#1]
I = PencilDrawing(im, 8, 1, 8, 1.0, 1.0);
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'PencilDrawing' is not defined
------------------
Please help! thanks!

**Comment by candycat1992** [comment]
You should make sure you have included PencilDrawing.m and the other files in the same path.
